# Generated by Django 4.0 on 2021-12-31 01:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferredMethodOfReceiving', models.JSONField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('onesies', models.BooleanField(default=False)),
                ('twoPieceOutfits', models.BooleanField(default=False)),
                ('sleepSack', models.BooleanField(default=False)),
                ('cribSheets', models.BooleanField(default=False)),
                ('crib', models.BooleanField(default=False)),
                ('bibs', models.BooleanField(default=False)),
                ('receivingBlankets', models.BooleanField(default=False)),
                ('burpCloths', models.BooleanField(default=False)),
                ('washcloths', models.BooleanField(default=False)),
                ('bottles', models.BooleanField(default=False)),
                ('stroller', models.BooleanField(default=False)),
                ('strollerType', models.CharField(blank=True, choices=[('double', 'Double'), ('single', 'Single')], max_length=20, null=True)),
                ('formula', models.BooleanField(default=False)),
                ('formulaType', models.CharField(blank=True, max_length=100, null=True)),
                ('diapers', models.BooleanField(default=False)),
                ('diapersSize', models.CharField(blank=True, max_length=100, null=True)),
                ('wipes', models.BooleanField(default=False)),
                ('otherInfantNeeds', models.TextField(blank=True, null=True)),
                ('shortSleeveShirts', models.BooleanField(default=False)),
                ('longSleeveShirts', models.BooleanField(default=False)),
                ('shorts', models.BooleanField(default=False)),
                ('longPants', models.BooleanField(default=False)),
                ('pajamas', models.BooleanField(default=False)),
                ('dressClothes', models.BooleanField(default=False)),
                ('dresses', models.BooleanField(default=False)),
                ('winterCoats', models.BooleanField(default=False)),
                ('swimwear', models.BooleanField(default=False)),
                ('holidayOutfit', models.BooleanField(default=False)),
                ('shoes', models.BooleanField(default=False)),
                ('toothbrush', models.BooleanField(default=False)),
                ('toothpaste', models.BooleanField(default=False)),
                ('deodorant', models.BooleanField(default=False)),
                ('soap', models.BooleanField(default=False)),
                ('shampoo', models.BooleanField(default=False)),
                ('ethnicHairCairProducts', models.BooleanField(default=False)),
                ('hairAccessories', models.BooleanField(default=False)),
                ('makeUpItems', models.BooleanField(default=False)),
                ('makeUpItemsDescription', models.TextField(blank=True, null=True)),
                ('schoolSupplies', models.TextField(blank=True, null=True)),
                ('toysGamesBooks', models.TextField(blank=True, null=True)),
                ('bedding', models.TextField(blank=True, null=True)),
                ('weightedBlanket', models.BooleanField(default=False)),
                ('otherNeeds', models.TextField(blank=True, null=True)),
                ('forChild', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.child')),
                ('forUser', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.user')),
            ],
        ),
    ]
