# Generated by Django 4.0 on 2022-02-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irequests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsrequest',
            old_name='ethnicHairCairProducts',
            new_name='ethnicHairCareProducts',
        ),
    ]
