# Generated by Django 4.0 on 2022-08-19 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('irequests', '0004_alter_itemsrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsrequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
