# Generated by Django 4.0 on 2021-12-31 01:45

import adminManagement.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoursEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('hoursWorked', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dataTableInfo', models.JSONField(default=adminManagement.models.hoursEntry.buildDefDict)),
                ('forVolunteer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='adminManagement.volunteer')),
            ],
        ),
    ]
