# Generated by Django 4.0 on 2021-12-30 18:35

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Unset', max_length=300)),
                ('city', models.CharField(default='Unset', max_length=300)),
                ('state', models.CharField(default='Unset', max_length=300)),
                ('zipCode', models.IntegerField(default=0)),
                ('country', models.CharField(default='USA', max_length=300)),
                ('cellPhone', models.BigIntegerField(default=0)),
                ('homePhone', models.BigIntegerField(default=0)),
                ('contactMethod', models.CharField(choices=[('cellPhRadio', 'Cell Phone Number'), ('homePhRadio', 'Home Phone Number'), ('emailRadio', 'Email Address')], default='emailRadio', max_length=300)),
                ('emailUpdateList', models.BooleanField(default=False)),
                ('remindUpdateList', models.BooleanField(default=False)),
                ('registrationProgress', models.CharField(default='Complete', max_length=300)),
                ('dataTableInfo', models.JSONField(default=accounts.models.userBasic.buildDefDict)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='safetyFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unset', max_length=300)),
                ('county', models.CharField(default='Unset', max_length=300)),
                ('planTimeLength', models.TextField(default='Unset', max_length=500)),
                ('workerName', models.CharField(default='Unset', max_length=300)),
                ('workerContact', models.TextField(default='Unset', max_length=300)),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='kinshipFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unset', max_length=300)),
                ('children', models.TextField(default='Unset')),
                ('placementRelation', models.TextField(default='Unset', max_length=500)),
                ('county', models.CharField(default='Unset', max_length=300)),
                ('workerName', models.CharField(default='Unset', max_length=300)),
                ('workerContact', models.TextField(default='Unset', max_length=300)),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='fosterFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unset', max_length=300)),
                ('county', models.CharField(default='Unset', max_length=300)),
                ('agency', models.CharField(default='Unset', max_length=300)),
                ('workerName', models.CharField(default='Unset', max_length=300)),
                ('workerContact', models.TextField(default='Unset', max_length=300)),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='Unset', max_length=300)),
                ('gender', models.CharField(default='Unset', max_length=300)),
                ('careType', models.CharField(choices=[('biological', 'Biological'), ('adopted', 'Adopted'), ('foster', 'Foster'), ('kinship', 'Kinship'), ('safety-plan', 'Safety-plan'), ('respite', 'Respite')], default='adopted', max_length=300)),
                ('newPlacement', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Unset', max_length=300)),
                ('age', models.IntegerField(default=0)),
                ('dateOfBirth', models.CharField(default='Unset', max_length=300)),
                ('clothesSize', models.CharField(default='Unset', max_length=300)),
                ('shoeSize', models.CharField(default='Unset', max_length=300)),
                ('specials', models.TextField(blank=True, null=True)),
                ('favorites', models.TextField(blank=True, null=True)),
                ('hasAllergy', models.BooleanField(default=False)),
                ('allergyDescription', models.TextField(blank=True, null=True)),
                ('dataTableInfo', models.JSONField(default=accounts.models.child.buildDefDict)),
                ('parent', models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='careType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unset', max_length=300)),
                ('adoptive', models.BooleanField(default=False)),
                ('foster', models.BooleanField(default=False)),
                ('kinship', models.BooleanField(default=False)),
                ('safety', models.BooleanField(default=False)),
                ('signature', models.CharField(default='NOT SIGNED', max_length=300)),
                ('date', models.CharField(default='Unset', max_length=300)),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='adoptiveFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unset', max_length=300)),
                ('adoptedChildren', models.TextField(default='Unset')),
                ('user', models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
