# Generated by Django 4.0 on 2022-02-12 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbasic',
            old_name='country',
            new_name='county',
        ),
        migrations.AlterField(
            model_name='child',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
