# Generated by Django 4.0 on 2022-08-19 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_adoptivefamily_name_remove_fosterfamily_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptivefamily',
            name='adoptedChildren',
        ),
        migrations.RemoveField(
            model_name='kinshipfamily',
            name='children',
        ),
        migrations.AddField(
            model_name='child',
            name='clothingGender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nopref', 'No preference')], default='male', max_length=40),
        ),
        migrations.AddField(
            model_name='child',
            name='relationship',
            field=models.CharField(default='Unset', max_length=30),
        ),
        migrations.AlterField(
            model_name='caretype',
            name='date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='caretype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caretype',
            name='signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='careType',
            field=models.CharField(choices=[('biological', 'Biological'), ('adopted', 'Adopted'), ('foster', 'Foster'), ('kinship', 'Kinship'), ('safety-plan', 'Safety-plan'), ('respite', 'Respite')], default='adopted', max_length=15),
        ),
        migrations.AlterField(
            model_name='child',
            name='clothesSize',
            field=models.CharField(choices=[('preemie', 'Preemie'), ('nb', 'NB'), ('0-3m', '0-3m'), ('3m', '3m'), ('3-6m', '3-6m'), ('6m', '6m'), ('6-9m', '6-9m'), ('9m', '9m'), ('9-12m', '9-12m'), ('12m', '12m'), ('12-18m', '12-18m'), ('18m', '18m'), ('18-24m', '18-24m'), ('24m', '24m'), ('2t', '2t'), ('3t', '3t'), ('4t', '4t'), ('5t', '5t'), ('4/5', '4/5'), ('5', '5'), ('5/6', '5/6'), ('6', '6'), ('6/7', '6/7'), ('7', '7'), ('7/8', '7/8'), ('8', '8'), ('8/10', '8/10'), ('10', '10'), ('10/12', '10/12'), ('12', '12'), ('12/14', '12/14'), ('14', '14'), ('14/16', '14/16'), ('16', '16'), ('16/18', '16/18'), ('18', '18'), ('adultSmall', 'Adult Small'), ('adultMedium', 'Adult Medium'), ('adultLarge', 'Adult Large'), ('adultXLarge', 'Adult X Large')], default='preemie', max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='firstName',
            field=models.CharField(default='Unset', max_length=50),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Prefer not to specify')], default='male', max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='newPlacement',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
        ),
        migrations.AlterField(
            model_name='child',
            name='shoeSize',
            field=models.CharField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='agency',
            field=models.CharField(default='Unset', max_length=70),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='county',
            field=models.CharField(default='Unset', max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='workerContact',
            field=models.TextField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='fosterfamily',
            name='workerName',
            field=models.CharField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='kinshipfamily',
            name='county',
            field=models.CharField(default='Unset', max_length=50),
        ),
        migrations.AlterField(
            model_name='kinshipfamily',
            name='placementRelation',
            field=models.TextField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='kinshipfamily',
            name='workerContact',
            field=models.TextField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='kinshipfamily',
            name='workerName',
            field=models.CharField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyfamily',
            name='county',
            field=models.CharField(default='Unset', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyfamily',
            name='planTimeLength',
            field=models.TextField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyfamily',
            name='workerContact',
            field=models.TextField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='safetyfamily',
            name='workerName',
            field=models.CharField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='userbasic',
            name='address',
            field=models.CharField(default='Unset', max_length=100),
        ),
        migrations.AlterField(
            model_name='userbasic',
            name='city',
            field=models.CharField(default='Unset', max_length=50),
        ),
        migrations.AlterField(
            model_name='userbasic',
            name='contactMethod',
            field=models.CharField(choices=[('cellPhRadio', 'Cell Phone Number'), ('homePhRadio', 'Home Phone Number'), ('emailRadio', 'Email Address')], default='emailRadio', max_length=50),
        ),
        migrations.AlterField(
            model_name='userbasic',
            name='county',
            field=models.CharField(default='USA', max_length=50),
        ),
        migrations.AlterField(
            model_name='userbasic',
            name='registrationProgress',
            field=models.CharField(default='Complete', max_length=50),
        ),
        migrations.AlterField(
            model_name='userbasic',
            name='state',
            field=models.CharField(default='Unset', max_length=30),
        ),
    ]
