# Generated by Django 4.0 on 2022-08-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_adoptivefamily_adoptedchildren_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='clothingGender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nopref', 'No preference')], default='nopref', max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unspecified', 'Prefer not to specify')], default='unspecified', max_length=40),
        ),
    ]
