# Generated by Django 4.0 on 2022-08-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceActive', models.BooleanField(default=False)),
                ('messageQueue', models.JSONField(default=list)),
                ('errorMessages', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
